[package]
name = "cln4keet"
version = "0.1.0"
edition = "2021"

[dependencies]
clightningrpc-plugin = "0.3.0-beta.5"
rest-api = { path = "../rest-api/" }
serde_json = "1.0"
rocket = "0.5.0-rc.2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = "z"
strip = true
