[package]
name = "rest-api"
version = "0.1.0"
edition = "2021"

[dependencies]
clightningrpc-common = "0.3.0-beta.2"
rocket = "0.5.0-rc.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rocket_okapi = { version ="0.8.0-rc.2",  features = ["swagger"] }
